version: '3'

services:
  fe-certificate:
    container_name: fe-certificate
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - .env.production
    command: yarn start
    restart: always
    ports:
      - '3006:80'
