pipeline {
    agent any
    stages {
        stage('Deployy') {
            steps {
                sshagent(['ec2-credential']) {
                    sh '''
                        mkdir hello
                        cd /home/blockchain/frontend &&
                        git pull &&
                        docker-compose up -d --build
                        "
                    '''
                }
            }
        }
    }
}
