pipeline {
    agent any
    stages {
        stage('Deploy') {
            steps {
                sshagent(['vinhphan-root-keys']) {
                    sh '''
                        ssh root@194.163.180.21 "
                        cd /home/blockchain/frontend &&
                        git pull &&
                        docker-compose up -d --build
                        "
                    '''
                }
            }
        }
    }
}
