import Head from 'next/head'
import { MainLayout } from '@/layouts'
import Image1 from '../../public/landing-page1.jpeg'
import Image2 from '../../public/landing-page2.jpg'
import Image3 from '../../public/landing-page3.webp'
import Image from 'next/image'
import { Button, TextField } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Blockchain-Certificate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-center bg-no-repeat bg-[url('https://binhdinh.vbcc.vn/upload/21325/20210506/Group_48_b0114.png')] bg-gray-700 bg-blend-multiply">
        <div className="px-4 mx-auto max-w-screen-xl text-center py-24 lg:py-56">
          <h1 className="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl">
            <span className="text-transparent bg-clip-text bg-gradient-to-r to-emerald-600 from-sky-400">
              Văn bằng chứng chỉ
            </span>
          </h1>
          <p className="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48">
            Chúng tôi mang đến một giải pháp hoàn toàn mới trong việc xác thực và lưu trữ văn bằng
            chứng chỉ số. Công bằng - Minh bạch - Uy tín đã làm nên thương hiệu của chúng tôi !
          </p>
          <div className="flex flex-col space-y-4 sm:flex-row sm:justify-center sm:space-y-0 sm:space-x-4">
            <a
              href="#"
              className="inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900"
            >
              Liên hệ
              <svg
                aria-hidden="true"
                className="ml-2 -mr-1 w-4 h-4"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fillRule="evenodd"
                  d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                  clipRule="evenodd"
                ></path>
              </svg>
            </a>
            <a
              href="#"
              className="inline-flex justify-center hover:text-gray-900 items-center py-3 px-5 text-base font-medium text-center text-white rounded-lg border border-white hover:bg-gray-100 focus:ring-4 focus:ring-gray-400"
            >
              Tìm hiểu thêm
            </a>
          </div>
        </div>
      </section>
      <div
        className=" p-4 bg-white rounded-lg md:p-8 dark:bg-gray-800 shadow"
        id="stats"
        role="tabpanel"
        aria-labelledby="stats-tab"
      >
        <dl className="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 gap-20 p-4 mx-auto text-gray-900 dark:text-white sm:p-8">
          <div className="flex flex-col items-center justify-center">
            <dt className="mb-2 text-3xl font-extrabold">50M+</dt>
            <dd className="text-gray-500 dark:text-gray-400">Người tiêu dùng</dd>
          </div>
          <div className="flex flex-col items-center justify-center">
            <dt className="mb-2 text-3xl font-extrabold">66+</dt>
            <dd className="text-gray-500 dark:text-gray-400">Đối tác</dd>
          </div>
          <div className="flex flex-col items-center justify-center">
            <dt className="mb-2 text-3xl font-extrabold">1000+</dt>
            <dd className="text-gray-500 dark:text-gray-400">Bài viết</dd>
          </div>
        </dl>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 ">
        <Image
          src={Image1}
          alt=""
          className="w-full h-60 lg:h-96 sm:h-80 md:h-80 rounded shadow"
        ></Image>
        <Image
          src={Image2}
          alt=""
          className="w-full h-60 lg:h-96 sm:h-80 md:h-80 rounded shadow"
        ></Image>
        <Image
          src={Image3}
          alt=""
          className="w-full h-60 lg:h-96 sm:h-80 md:h-80 rounded shadow"
        ></Image>
      </div>
      <div className="grid mb-8 border border-gray-200 rounded-lg shadow-sm dark:border-gray-700 md:mb-12 md:grid-cols-2">
        <figure className="flex flex-col items-center justify-center p-8 text-center bg-white border-b border-gray-200 rounded-t-lg md:rounded-t-none md:rounded-tl-lg md:border-r dark:bg-gray-800 dark:border-gray-700">
          <blockquote className="max-w-2xl mx-auto mb-4 text-gray-500 lg:mb-8 dark:text-gray-400">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Cảm nhận của học sinh
            </h3>
            <p className="my-4">
              Bản thân là học sinh chưa từng nghĩ mình sẽ có một công nghệ mới tuyệt vời có thể dễ
              dàng xác thực văn bằng đến vậy.
            </p>
          </blockquote>
          <figcaption className="flex items-center justify-center space-x-3">
            <img
              className="rounded-full w-9 h-9"
              src="https://scontent.fsgn5-2.fna.fbcdn.net/v/t39.30808-6/299736055_2554035778071516_385462712747607399_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=VxsTVx5XYu8AX_RhYd2&_nc_ht=scontent.fsgn5-2.fna&oh=00_AfB9xr9aUIw_7puL8Ha6wrWYgnmqqLHYcnYy3-T82ZUr0Q&oe=6463AAAA"
              alt="profile picture"
            />
            <div className="space-y-0.5 font-medium dark:text-white text-left">
              <div>Trần Thanh Long</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Sinh viên HUFLIT</div>
            </div>
          </figcaption>
        </figure>
        <figure className="flex flex-col items-center justify-center p-8 text-center bg-white border-b border-gray-200 rounded-t-lg md:rounded-t-none md:rounded-tl-lg md:border-r dark:bg-gray-800 dark:border-gray-700">
          <blockquote className="max-w-2xl mx-auto mb-4 text-gray-500 lg:mb-8 dark:text-gray-400">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Giảng viên nói gì ?
            </h3>
            <p className="my-4">
              Ban đầu cứ nghĩ công nghệ mới rất khó ứng dụng vào thực tế nhưng hoàn toàn trái ngược.
            </p>
          </blockquote>
          <figcaption className="flex items-center justify-center space-x-3">
            <img
              className="rounded-full w-9 h-9"
              src="https://images2.thanhnien.vn/Uploaded/thuyhang/2022_11_09/hinh-tho-day-1-7814.jpg"
              alt="profile picture"
            />
            <div className="space-y-0.5 font-medium dark:text-white text-left">
              <div>Trần Thành Công</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Giảng viên tại Đại học Bách Khoa
              </div>
            </div>
          </figcaption>
        </figure>
        <figure className="flex flex-col items-center justify-center p-8 text-center bg-white border-b border-gray-200 rounded-t-lg md:rounded-t-none md:rounded-tl-lg md:border-r dark:bg-gray-800 dark:border-gray-700">
          <blockquote className="max-w-2xl mx-auto mb-4 text-gray-500 lg:mb-8 dark:text-gray-400">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Phụ huynh trải nghiệm
            </h3>
            <p className="my-4">
              Trước đây việc xác thực văn bằng chứng chỉ tiêu tốn rất nhiều thời gian nhưng giờ tôi
              không còn phải lo nữa. Rất tuyệt vời !
            </p>
          </blockquote>
          <figcaption className="flex items-center justify-center space-x-3">
            <img
              className="rounded-full w-9 h-9"
              src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/avatars/karen-nelson.png"
              alt="profile picture"
            />
            <div className="space-y-0.5 font-medium dark:text-white text-left">
              <div>Trần Xuân Trang</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Phụ huynh</div>
            </div>
          </figcaption>
        </figure>
        <figure className="flex flex-col items-center justify-center p-8 text-center bg-white border-b border-gray-200 rounded-t-lg md:rounded-t-none md:rounded-tl-lg md:border-r dark:bg-gray-800 dark:border-gray-700">
          <blockquote className="max-w-2xl mx-auto mb-4 text-gray-500 lg:mb-8 dark:text-gray-400">
            <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
              Trung tâm Anh Ngữ Apex Leader
            </h3>
            <p className="my-4">
              Từ nay việc xác thực văn bằng chứng chỉ đã trở nên dễ dàng hơn bao giờ hết cảm ơn các
              bên liên quan cho đã ra đời một sản phẩm mang tính cách mạng !
            </p>
          </blockquote>
          <figcaption className="flex items-center justify-center space-x-3">
            <img
              className="rounded-full w-9 h-9"
              src="https://znews-photo.zingcdn.me/w660/Uploaded/neg_esfjaex/2023_02_26/shark_Thuyanh_1_1.jpg"
              alt="profile picture"
            />
            <div className="space-y-0.5 font-medium dark:text-white text-left">
              <div> Nguyễn Ngọc Thủy</div>
              <div className="text-sm text-gray-500 dark:text-gray-400">Chủ tịch Apex Leader</div>
            </div>
          </figcaption>
        </figure>
      </div>
      <div className="flex justify-center">
        <form className="flex flex-col gap-4 shadow p-5 w-full lg:w-1/3 sm:w-full">
          <div className="font-bold text-red-600 text-center">Tra cứu văn bằng chứng chỉ</div>
          <div>
            <div className="mb-2 block">
              <label htmlFor="name" />
            </div>
            <TextField label="Tra cứu" name="search" required={true} fullWidth />
          </div>
          <Button type="submit" variant="outlined">
            Tra cứu
          </Button>
        </form>
      </div>
    </>
  )
}

Home.Layout = MainLayout
