export const recipientProfileDefaultForm = {
  id: '',
  iU: '',
  iSt: '',
  departmentName: '',
  studentName: '',
  universityName: '',
  dateOfBirth: '',
  year: '2023',
  nameCourse: '',
  major: '',
  placeOfBirth: 'TPHCM',
  nation: 'Kinh',
  ranking: '',
  formOfTraining: '',
  CGPA: 5,
  gender: '',
}
