const majorOptions = [
  { value: 'Công nghệ thông tin', label: 'Công nghệ thông tin' },
  { value: 'Kỹ thuật phần mềm', label: 'Kỹ thuật phần mềm' },
  { value: 'Hệ thống thông tin', label: 'Hệ thống thông tin' },
  { value: 'Khoa học máy tính', label: 'Khoa học máy tính' },
  { value: 'Quản trị mạng', label: 'Quản trị mạng' },
  { value: 'Truyền thông đa phương tiện', label: 'Truyền thông đa phương tiện' },
  { value: 'Kỹ thuật điện tử', label: 'Kỹ thuật điện tử' },
  { value: 'Kỹ thuật viễn thông', label: 'Kỹ thuật viễn thông' },
  { value: 'Kỹ thuật máy tính', label: 'Kỹ thuật máy tính' },
  { value: 'Công nghệ kỹ thuật điện', label: 'Công nghệ kỹ thuật điện' },
  { value: 'Công nghệ kỹ thuật điện tử', label: 'Công nghệ kỹ thuật điện tử' },
  { value: 'Kỹ thuật ô tô', label: 'Kỹ thuật ô tô' },
  { value: 'Kỹ thuật xây dựng', label: 'Kỹ thuật xây dựng' },
  { value: 'Kỹ thuật cơ khí', label: 'Kỹ thuật cơ khí' },
  { value: 'Kỹ thuật công trình xây dựng', label: 'Kỹ thuật công trình xây dựng' },
  { value: 'Kiến trúc', label: 'Kiến trúc' },
  { value: 'Quản trị kinh doanh', label: 'Quản trị kinh doanh' },
  { value: 'Marketing', label: 'Marketing' },
  { value: 'Tài chính ngân hàng', label: 'Tài chính ngân hàng' },
  { value: 'Kế toán', label: 'Kế toán' },
  { value: 'Quản trị nhân lực', label: 'Quản trị nhân lực' },
  { value: 'Quản trị khách sạn', label: 'Quản trị khách sạn' },
  { value: 'Du lịch và lữ hành', label: 'Du lịch và lữ hành' },
  { value: 'Ngôn ngữ Anh', label: 'Ngôn ngữ Anh' },
  { value: 'Ngôn ngữ Nhật', label: 'Ngôn ngữ Nhật' },
  { value: 'Ngôn ngữ Hàn Quốc', label: 'Ngôn ngữ Hàn Quốc' },
  { value: 'Ngôn ngữ Trung Quốc', label: 'Ngôn ngữ Trung Quốc' },
  { value: 'Văn hóa học', label: 'Văn hóa học' },
  { value: 'Lịch sử', label: 'Lịch sử' },
  { value: 'Triết học', label: 'Triết học' },
  { value: 'Văn học', label: 'Văn học' },
  { value: 'Đông phương học', label: 'Đông phương học' },
  { value: 'Luật học', label: 'Luật học' },
  { value: 'Khoa học xã hội', label: 'Khoa học xã hội' },
  { value: 'Tâm lý học', label: 'Tâm lý học' },
  { value: 'Sư phạm Tiếng Anh', label: 'Sư phạm Tiếng Anh' },
  { value: 'Sư phạm Tiếng Việt', label: 'Sư phạm Tiếng Việt' },
  { value: 'Sư phạm Toán học', label: 'Sư phạm Toán học' },
  { value: 'Sư phạm Vật lý', label: 'Sư phạm Vật lý' },
  { value: 'Sư phạm Hóa học', label: 'Sư phạm Hóa học' },
  { value: 'Sư phạm Sinh học', label: 'Sư phạm Sinh học' },
  { value: 'Sư phạm Ngữ văn', label: 'Sư phạm Ngữ văn' },
  { value: 'Sư phạm Lịch sử', label: 'Sư phạm Lịch sử' },
  { value: 'Sư phạm Địa lý', label: 'Sư phạm Địa lý' },
  { value: 'Sư phạm Công nghệ', label: 'Sư phạm Công nghệ' },
  { value: 'Y học', label: 'Y học' },
  { value: 'Nha khoa', label: 'Nha khoa' },
  { value: 'Dược học', label: 'Dược học' },
  { value: 'Kỹ thuật y sinh', label: 'Kỹ thuật y sinh' },
  { value: 'Khoa học máy tính ứng dụng', label: 'Khoa học máy tính ứng dụng' },
  { value: 'Hệ thống thông tin ứng dụng', label: 'Hệ thống thông tin ứng dụng' },
  { value: 'Quản trị mạng ứng dụng', label: 'Quản trị mạng ứng dụng' },
]

export { majorOptions }
