const nationOptions = [
  { value: 'Ba-na', label: 'Ba-na' },
  { value: 'Bru-Vân Kiều', label: 'Bru-Vân Kiều' },
  { value: 'Brâu', label: 'Brâu' },
  { value: 'Bố Y', label: 'Bố Y' },
  { value: 'Chu-ru', label: 'Chu-ru' },
  { value: 'Chăm', label: 'Chăm' },
  { value: 'Chơ-ro', label: 'Chơ-ro' },
  { value: 'Chứt', label: 'Chứt' },
  { value: 'Co', label: 'Co' },
  { value: 'Cơ-ho', label: 'Cơ-ho' },
  { value: 'Cơ-tu', label: 'Cơ-tu' },
  { value: 'Cống', label: 'Cống' },
  { value: 'Cờ lao', label: 'Cờ lao' },
  { value: 'Dao', label: 'Dao' },
  { value: 'Gia Rai', label: 'Gia Rai' },
  { value: 'Giáy', label: 'Giáy' },
  { value: 'Gié-Triêng', label: 'Gié-Triêng' },
  { value: 'Hmông', label: 'Hmông' },
  { value: 'Hoa', label: 'Hoa' },
  { value: 'Hrê', label: 'Hrê' },
  { value: 'Hà Nhì', label: 'Hà Nhì' },
  { value: 'Khác', label: 'Khác' },
  { value: 'Kháng', label: 'Kháng' },
  { value: 'Khơ Me', label: 'Khơ Me' },
  { value: 'Khơmú', label: 'Khơmú' },
  { value: 'Kinh', label: 'Kinh' },
  { value: 'La Ha', label: 'La Ha' },
  { value: 'La Hủ', label: 'La Hủ' },
  { value: 'La-chí', label: 'La-chí' },
  { value: 'Lào', label: 'Lào' },
  { value: 'LôLô', label: 'LôLô' },
  { value: 'Lự', label: 'Lự' },
  { value: 'Mnông', label: 'Mnông' },
  { value: 'Mường', label: 'Mường' },
  { value: 'Mạ', label: 'Mạ' },
  { value: 'Mảng', label: 'Mảng' },
  { value: 'Ngái', label: 'Ngái' },
  { value: 'Nùng', label: 'Nùng' },
  { value: 'Phù Lá', label: 'Phù Lá' },
  { value: 'Pu Piéo', label: 'Pu Piéo' },
  { value: 'Pà Thẻn', label: 'Pà Thẻn' },
  { value: 'Ra-glay', label: 'Ra-glay' },
  { value: 'Rơ-măm', label: 'Rơ-măm' },
  { value: 'Si La', label: 'Si La' },
  { value: 'Sán Cháy', label: 'Sán Cháy' },
  { value: 'Sán Diù', label: 'Sán Diù' },
  { value: 'Ta-ôi', label: 'Ta-ôi' },
  { value: 'Thái', label: 'Thái' },
  { value: 'Thổ', label: 'Thổ' },
  { value: 'Tày', label: 'Tày' },
  { value: "X'tiêng", label: "X'tiêng" },
  { value: 'Xinh-mun', label: 'Xinh-mun' },
  { value: 'Xơ-đăng', label: 'Xơ-đăng' },
  { value: 'Ê-đê', label: 'Ê-đê' },
  { value: 'Ơ-đu', label: 'Ơ-đu' },
]

export { nationOptions }
